eureka: 
  instance: 
    instance-id: ${spring.cloud.client.ip-address}:${server.port}    
hystrix:
  stream: 
    maxConcurrentConnections: 10
  command:
    default:
      execution:
        timeout:
          enabled: false
feign: 
  client: 
    config: 
      default: 
        connectTimeout: 10000
        readTimeout: 30000
      his-service: 
        connectTimeout: 30000
        readTimeout: 300000
ribbon:
  connectTimeout: 30000
  readTimeout: 300000
  socketTimeout: 300000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
management: 
  endpoint: 
    health: 
      show-details: ALWAYS
  endpoints:
    web: 
      exposure:
        include: "*"
server: 
  tomcat: 
    accept-count: 20 
    max-connections: 10 # Maximum number of connections that the server accepts and processes at any given time.
    max-threads: 10 # Maximum number of worker threads.
    min-spare-threads: 5 # Minimum number of worker threads.
spring: 
  cloud: 
    stream: 
      kafka: 
        binder: 
          brokers: 10.0.0.110
  sleuth:
    sampler:
      probability: 1.0
  zipkin: 
    sender: 
      type: KAFKA
  kafka:
    bootstrap-servers:
    - 10.0.0.110:9092
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cache:
    type: REDIS
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
      write-null-map-values: false
      write-empty-json-arrays: false
    deserialization:
      accept-single-value-as-array: true
      accept-empty-array-as-null-object: true
  redis: 
    database: 0
    host: 10.0.0.110
    port: 6379
    password: "{cipher}AQBSQDWwxoE1MOTovH4bgd6HwPk3m0wMaN0Btc0Vc4Pl/K9NzPXOzl88+JcmnkZAGQYwJ1kLQW0RV41r7a0n33VmwBXXpwIM/3Z3zrERNChRJtAV6o92yjN9HaY2iaSk6fIBTUSbTWiDyLFyDcTQqLTmueA/ZSNWW4bXTQIscjkvfAyoxqOBFXa4nQ3DNYp1gz5nmw7fCQewnj19mENZKmEhy6Cqi9264EMEIFZmNAKpcyELjoDFvCZxGMtK1T1FhVwinb5Q1Eg8vdFZfHKAZzkBJfoySpSt8QPE0rToZxbrzeU3TOX4lOScb9HcXKtexy0nX440OJjEU+1ec6V2yUF3vTvj+TijfXEtWqBLyroc+aR2BG1lVX4nUMWI5yRYhow="
    lettuce: 
      pool: 
        max-wait: -1
        max-active: 10
        max-idle: 10
        min-idle: 0
    timeout: 2000  
  data: 
    mongodb: 
      #authentication-database: admin
      #database: ehr
      host: 10.0.0.162
      username: root
      port: 27017
cloudhub: 
  access-token-url: "http://111.230.166.38/mwp/token/api/getAccessToken"
  api-url: "http://111.230.166.38/mwp"
  client-id: "{cipher}AQAfHfBguC8b3snvlQIPgFkVL9ylOmwiHNTXMm24fxtFxkDKQ5ONdyTSNvQpmY1x0n9XrYQkgiZABrThVm9JjU43r+W1fYCYoqS3zk3IfQ/yiqUnqPulOoL22fxWPqb5q0WuyrEJUZcj/J5WbbBw7hPI/s4aIMdFFNHNoeWC2zarFaE+pLpfkpiwWkPT416ACf2PEFuhIof5toq65dt77DZFc2kYhHRUn9EXv0vy9MLG9pr7AOjcmKAac5RFqziB/pab5/sjsNpkL63DpZX1nrniTeHGWgOBX3bXhzPTnssJN3PcRtCUCAWpkUbjAWu2+YkLlBPfe7x3xQ862gisqi0dlAK3DDKwwnSeXChJEfS9FVaBqG8uaUO8a73KYrCwT/8BWNGO5n/ucNoH6lk6cxLp"
  secret: "{cipher}AQB6cFsC0oLBn4Zo9x1hDJqt00EYvFBqxBX6xHkZbZpHrR81cE14srPRyTPAy1s4qKDPDB7a3T4Ojddt4Sb3Ml+WMiypxlosbzQjzg97/nKZ+/IhzHYym9ODIhtgnKqW6/mXbQUVI3naqeNtOUDI3aTX7B0aitOaG/3vetH1VUE6VBI37zNuul5ZfMStIHx1tgS1dBUgJJkr55NcBqoJ8UkiQA8QNsO4S+PFdGHtRYtKaKT1MnIWPQJbTLWVUFhNByZ3/4W+nxvgJfk/po3bBWYRczlOnuDJfodmegO1O4GUUOkB/QRH86ebFYGk2ykGWXjf4A/ilU0Akh/BavTUFYFmpFG+ygrDQ0d53PxQ/N2waZ6P/1zXNLfEWf/4EtVRDwOnRD8+7YM/wFGj/bzLTnVxzcq5Nug0iSuuZtQLPaDTMg=="
kingdeehit:
  api-gateway: "https://dev.mhealth100.com/gateway"
logging:
  config: classpath:log4j2-development.yml
  level: 
    com.kingdeehit.cloud: debug
    org.apache.kafka: info
    org.apache.flume: info
    com.netflix.discovery: info    
    com.kingdeehit.cloud.social.wechat.api: debug
    org.springframework.kafka: info
    org.apache.http: info
    io.lettuce: info  