server:
  port: 5220
logging: 
  config: classpath:log4j2-development.yml
spring: 
  cloud: 
    stream: 
      kafka: 
        binder: 
          brokers: 10.0.0.110
          defaultBrokerPort: 9092
          zkNodes: 10.0.0.110
          defaultZkPort: 2181