server:
  protocol: org.apache.coyote.http11.Http11NioProtocol
logging: 
  config: classpath:log4j2-development.yml
feign: 
  hystrix: 
    enabled: false
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 1000
spring:
  cloud: 
    stream: 
      kafka: 
        binder: 
          brokers: 10.0.0.110
          defaultBrokerPort: 9092
          zkNodes: 10.0.0.110
          defaultZkPort: 2181
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate    
  redis: 
    database: 0
    host: 10.0.0.110
    port: 6379
    password: "{cipher}AQAQJ4OOZS2Tw8ErJk/6OWbOhfx7LtVJczr952yVAQK62KDNoVyDTLA6zfm4iW4jX7Yk0g2W5DoonZrH8RblQDpcV0whTTQctoEFlDKTIf5nbEto3V7sArU6HDxCBjXR9VWIlf3jFwCsoFFf72EO/SeFm4TweURZat+aCWkJDNR4GWZnfzgGL3MfRBtnlFXtKUz6iKayxLrkID7Vh5+BB2kQgBKe9oj+WQ+NKTAm2DbvD5p7O4mnVXbLWJqS/LCEuFpa59fF/XzNL3Spw/1k2wjstZy2A9i4TlDoJWpWtM1xQhGLqoUK64pWQJW/zQ+VLYrIH3UQJeO6Gmk5GLJ3fVtD66PKB2HPXjFCMZ4UtUexB/Tywi9e8UDARXhBGFwTLdo="
    jedis: 
      pool: 
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 2000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.0.162:3306/OP?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: kingdee8349
    druid: 
      initialSize: 10
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMills: 300000
      testOnBorrow: false
      testWhileIdle: true
      testOnReutrn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      useGlobalDataSourceStat: true